---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "uvarc-unified-service.fullname" . }}-ceph-pvc-data
  labels:
    {{- include "uvarc-unified-service.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # This doesn't really matter for a static PV
      storage: 100Gi
  volumeMode: Filesystem
  volumeName: {{ include "uvarc-unified-service.fullname" . }}-ceph-pv-data
  storageClassName: csi-cephfs-sc