---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uvarc-unified-service-rc-staff-dtn-cephfs-pvc-prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # This doesn't really matter for a static PV
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: uvarc-unified-service-rc-staff-dtn-cephfs-pv-test
  storageClassName: csi-cephfs-sc
  selector:
    matchLabels:
      app: "uvarc-unified-service"