apiVersion: batch/v1
kind: CronJob
metadata:
  name: uvarc-unified-service-sqs-reader
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sqs-reader
            image: ghcr.io/uvarc/uvarc-unified-service:develop
            imagePullPolicy: Always
            command:
              - /bin/sh
              - -c
              - python3 scripts/sqs-reader-utils.py
            resources:
              requests:
                memory: "100Mi"
                cpu: "50m"
              limits:
                memory: "100Mi"
                cpu: "50m"
            env:
            - name: QUEUE_URL
              value: "https://sqs.us-east-1.amazonaws.com/474683445819/uvarc_unified_storage_request_queue_raji"
            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: uvarc-unified-service-secret
                  key: AWS_CLIENT_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: uvarc-unified-service-secret
                  key: AWS_CLIENT_SECRET
          restartPolicy: OnFailure
