---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uvarc-unified-service-ceph-pvc-data-prod
  namespace: uvarc-unified-services
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # This doesn't really matter for a static PV
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: uvarc-unified-service-ceph-pv-data-prod
  storageClassName: csi-cephfs-sc