apiVersion: v1
kind: Service
metadata:
  name: uvarc-unified-service-prod
  namespace: uvarc-unified-services
spec:
  selector:
    app: uvarc-unified-service-prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
