name: Docker Build CI

on:
  push:
    branches:
      - 'develop'
      - 'main'
    tags:
      - 'prod-*.*'
  workflow_dispatch:
jobs:
  build-for-git:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set the env
        id: set_env
        run: echo "BUILD_PROJ=uvarc-unified-service" >> $GITHUB_ENV

      - name: Extract tag name for prod release
        if: startsWith(github.ref, 'refs/tags/prod-')
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
           yq eval ".image.tag = \"${TAG_NAME}\"" -i kubernetes/prod/values.yaml
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push service for develop branch
        if: github.ref == 'refs/heads/develop'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          target: service
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/uvarc/${{ env.BUILD_PROJ }}:${{ github.ref_name }}
            ghcr.io/uvarc/${{ env.BUILD_PROJ }}:latest

      - name: Build and push service for main branch
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          target: service
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/uvarc/${{ env.BUILD_PROJ }}:${{ github.ref_name }}
            ghcr.io/uvarc/${{ env.BUILD_PROJ }}:main

      - name: Build and push service for prod tag
        if: startsWith(github.ref, 'refs/tags/prod-')
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          target: service
          push: true
          tags: |
            ghcr.io/uvarc/${{ env.BUILD_PROJ }}:${{ env.TAG_NAME }}

      - name: Push Prod Version to main branch
        if: startsWith(github.ref, 'refs/tags/prod-')
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[skip ci] Update Version to Helm - ${{ env.IMAGE_TAG }}"
          branch: main
          file_pattern: 'kubernetes/prod/values.yaml'
          commit_user_name: GitHub Actions Bot
          commit_user_email: github@virginia.edu
          commit_author: GitHub Actions <github@virginia.edu>
